name: CI/CD Pipeline for Web App

on:
    push:
        branches:
            - lab7
    pull_request:
        branches:
            - lab7

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.2
            - run: flutter pub get

            - run: flutter analyze --no-fatal-warnings --no-fatal-infos lib/templates/lab7/ 

            - run: flutter test test/widget_test.dart

            - run: flutter build web --release lib/templates/lab7/main.dart
                
            - uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: build/web
    
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.2
            - run: flutter pub get
            - run: flutter build windows --release